if (NOT DEFINED ORIGINAL_FILE)
  message(FATAL_ERROR "Required ORIGINAL_FILE is not set")
endif ()

if (NOT DEFINED DEST_FILE)
  message(FATAL_ERROR "Required DEST_FILE is not set")
endif ()

if (NOT DEFINED VAR_NAMESPACE)
  message(FATAL_ERROR "Required VAR_NAMESPACE is not set")
endif ()

string(REGEX MATCH "([^/]+)$" VAR_NAME ${ORIGINAL_FILE})
string(REGEX REPLACE "\\.| |-" "_" VAR_NAME ${VAR_NAME})

file(READ ${ORIGINAL_FILE} DATA HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," DATA ${DATA})
file(WRITE "${DEST_FILE}" "// Generated file, do not edit\n")
file(APPEND "${DEST_FILE}" "#include \"embedded_file.h\"\n")
file(APPEND "${DEST_FILE}" "namespace ${VAR_NAMESPACE} {\n")
file(APPEND "${DEST_FILE}" "static const char ${VAR_NAME}_name[] = \"${VAR_NAME}\";\n")
file(APPEND "${DEST_FILE}" "static const unsigned char ${VAR_NAME}_tmp[] = {${DATA}};\n")
file(APPEND "${DEST_FILE}" "::visage::EmbeddedFile ${VAR_NAME} = { ${VAR_NAME}_name, ")
file(APPEND "${DEST_FILE}" "(const char*)${VAR_NAME}_tmp, sizeof(${VAR_NAME}_tmp) };\n")
file(APPEND "${DEST_FILE}" "}")
